// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"petstore/pkg/models/shared"
)

type AddPetRawSecurity struct {
	PetstoreAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type AddPetRawResponse struct {
	Body        []byte
	ContentType string
	// Successful operation
	Pet         *shared.Pet
	StatusCode  int
	RawResponse *http.Response
}
