// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeletePetSecurity struct {
	PetstoreAuth string `security:"scheme,type=oauth2,name=Authorization"`
}

type DeletePetRequest struct {
	APIKey *string `header:"style=simple,explode=false,name=api_key"`
	// Pet id to delete
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
}

type DeletePetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
