// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrderRequest struct {
	// ID of the order that needs to be deleted
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderId"`
}

type DeleteOrderResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
