// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteUserRequest struct {
	// The name that needs to be deleted
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

type DeleteUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
