// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetInventoryResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// successful operation
	GetInventory200ApplicationJSONObject map[string]int
}
