// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type LoginUserRequest struct {
	// The password for login in clear text
	Password *string `queryParam:"style=form,explode=true,name=password"`
	// The user name for login
	Username *string `queryParam:"style=form,explode=true,name=username"`
}

type LoginUserResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// successful operation
	LoginUser200ApplicationJSONString *string
	// successful operation
	LoginUser200ApplicationXMLString *string
}
