// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateUserRawRequest struct {
	// Update an existent user in the store
	RequestBody []byte `request:"mediaType=application/xml"`
	// name that needs to be updated
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

type UpdateUserRawResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
