// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"petstore/pkg/models/shared"
)

type UpdateUserJSONRequest struct {
	// Update an existent user in the store
	User *shared.User `request:"mediaType=application/json"`
	// name that needs to be updated
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

type UpdateUserJSONResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
