// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PetStatusEnum - pet status in the store
type PetStatusEnum string

const (
	PetStatusEnumAvailable PetStatusEnum = "available"
	PetStatusEnumPending   PetStatusEnum = "pending"
	PetStatusEnumSold      PetStatusEnum = "sold"
)

func (e PetStatusEnum) ToPointer() *PetStatusEnum {
	return &e
}

func (e *PetStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "available":
		fallthrough
	case "pending":
		fallthrough
	case "sold":
		*e = PetStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PetStatusEnum: %v", v)
	}
}

// Pet - Create a new pet in the store
type Pet struct {
	Category  *Category `json:"category,omitempty" form:"name=category,json"`
	ID        *int64    `json:"id,omitempty" form:"name=id"`
	Name      string    `json:"name" form:"name=name"`
	PhotoUrls []string  `json:"photoUrls" form:"name=photoUrls"`
	// pet status in the store
	Status *PetStatusEnum `json:"status,omitempty" form:"name=status"`
	Tags   []Tag          `json:"tags,omitempty" form:"name=tags,json"`
}
